[package]
name = "ctf-tools"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
elf-utilities = "0.2.8"
num-traits="0.2"
num-derive="0.3"
